package org.tvtower.db.constants;

public class Country extends TVTEnum {

	//https://de.wikipedia.org/wiki/Liste_der_Kfz-Nationalit%C3%A4tszeichen
	Country() {
		add("A","Austria");
		add("AFG","Afghanistan");
		add("AM","Armenia");
		add("AUS","Australia");
		add("AZ","Azerbaijan");
		add("B","Belgium");
		add("BF","Burkina Faso");
		add("BIH","Bosnia and Herzegovina");
		add("BM","Bermudas");
		add("BG","Bulgeria");
		add("BOL","Bolivia");
		add("BR","Brazil");
		add("BW","Republic of Botswana");
		add("C","Cuba");
		add("CDN","Canada");
		add("CH","Switzerland");
		add("CHN","China");
		add("CL","Sri Lanka");
		add("CO","Colombia");
		add("CS","Tchechoslovakia");
		add("CZ","Czech Republic");
		add("D","Germany");
		add("DDR","GDR");
		add("DK","Denmark");
		add("EST","Estonia");
		add("E","Spain");
		add("F","France");
		add("FIN","Finland");
		add("FL","Liechtenstein");
		add("G","Gabon");
		add("GB","United Kingdom");
		add("GE","Georgia");
		add("GH","Ghana");
		add("GR", "Greece");
		add("H","Hungary");
		add("HK","Hongkong");
		add("HR","Kroatia");
		add("I","Italy");
		add("IL","Israel");
		add("IND","India");
		add("IR","Iran");
		add("IRL","Ireland");
		add("IS","Iceland");
		add("J","Japan");
		add("JOR","Jordan");
		add("KN","Greenland");
		add("KSA","Saudi Arabia");
		add("L","Luxembourg");
		add("LT","Lithuania");
		add("LV","Latvia");
		add("M", "Malta");
		add("MA","Marocco");
		add("MEX","Mexico");
		add("MNE","Montenegro");
		add("N","Norway");
		add("NL","Netherlands");
		add("NZ","New Zealand");
		add("P","Portugal");
		add("PA","Panama");
		add("PE","Peru");
		add("PL","Poland");
		add("Q","Qatar");
		add("RA","Argentina");
		add("RC","Taiwan");
		add("RI","Indonesia");
		add("RM","Republic of Moldavia");
		add("RO","Romania");
		add("ROK","South Korea");
		add("RP","Rep. of the Philippines");
		add("RUS","Russia");
		add("S","Sweden");
		add("SCO","Scotland");
		add("SRB","Serbia");
		add("SU","Soviet Union");
		add("T","Thailand");
		add("TN","Tunesia");
		add("TR","Turkey");
		add("UA","Ukraine");
		add("UAE","United Arab Emirates");
		add("USA","USA");
		add("YU","Yugoslavia");
		add("ZA","South Africa");
		add("ZW","Zimbabwe");
	}
}
