/*
 * generated by Xtext 2.25.0 and then adapted
 */
package org.tvtower.db.validation;

import org.eclipse.xtext.preferences.PreferenceKey;
import org.eclipse.xtext.util.IAcceptor;
import org.eclipse.xtext.validation.ConfigurableIssueCodesProvider;
import org.eclipse.xtext.validation.SeverityConverter;

@SuppressWarnings("restriction")
public class DatabaseConfigurableIssueCodesProvider extends ConfigurableIssueCodesProvider {
	protected static final String ISSUE_CODE_PREFIX = "org.tvtower.db.";

//	public static final String DEPRECATED_MODEL_PART = ISSUE_CODE_PREFIX + "deprecatedModelPart";
	public static final String TRIGGERED_NEWS_THREAD = ISSUE_CODE_PREFIX + "triggeredNewsThread";
	public static final String TRIGGERED_NEWS_GENRE = ISSUE_CODE_PREFIX + "triggeredNewsGenre";
	public static final String TRIGGERED_NEWS_UNIQUENESS = ISSUE_CODE_PREFIX + "triggeredNewsUniqueness";
	public static final String PERSON_SPOOF_NAME = ISSUE_CODE_PREFIX + "personSpoofName";
	public static final String PERSON_NAME_ENDING = ISSUE_CODE_PREFIX + "personNameEnding";
	public static final String ROLE_UNDEFINED_GENDER = ISSUE_CODE_PREFIX + "roleUndefinedGender";
	public static final String UNSUPPORTED_ATTRIBUTE = ISSUE_CODE_PREFIX + "unsupportedAttribute";
	// not issue code but boolean
	public static final String VALIDATTE_EFFECT_ACTIVATION = ISSUE_CODE_PREFIX + "effectActivation";

	@Override
	protected void initialize(IAcceptor<PreferenceKey> acceptor) {
		super.initialize(acceptor);
//		acceptor.accept(create(DEPRECATED_MODEL_PART, SeverityConverter.SEVERITY_WARNING));
		acceptor.accept(create(TRIGGERED_NEWS_THREAD, SeverityConverter.SEVERITY_WARNING));
		acceptor.accept(create(TRIGGERED_NEWS_GENRE, SeverityConverter.SEVERITY_WARNING));
		acceptor.accept(create(TRIGGERED_NEWS_UNIQUENESS, SeverityConverter.SEVERITY_WARNING));
		acceptor.accept(create(PERSON_SPOOF_NAME, SeverityConverter.SEVERITY_WARNING));
		acceptor.accept(create(PERSON_NAME_ENDING, SeverityConverter.SEVERITY_WARNING));
		acceptor.accept(create(ROLE_UNDEFINED_GENDER, SeverityConverter.SEVERITY_WARNING));
		acceptor.accept(create(UNSUPPORTED_ATTRIBUTE, SeverityConverter.SEVERITY_ERROR));

		acceptor.accept(create(VALIDATTE_EFFECT_ACTIVATION, "false"));
	}
}
