/*
 * generated by Xtext 2.23.0
 */
package org.tvtower.db.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith
import org.tvtower.db.database.Database
import org.junit.Assert

@RunWith(XtextRunner)
@InjectWith(DatabaseInjectorProvider)
class DatabaseParsingTest {
	@Inject
	ParseHelper<Database> parseHelper

	@Test
	def void emptyDb() {
		'''
		<?xml version="1.0" encoding="utf-8"?>
		<tvtdb>
			<version value="3" />
		</tvtdb>
		'''.noErrors
	}

	@Test
	def void roles() {
		'''
		<?xml version="1.0" encoding="utf-8"?>
		<tvtdb>
			<version value="3" />
			<programmeroles>
				<programmerole guid="script-roles-ron-001" first_name="Miranda" last_name="Jones" title="Dr." gender="2" />
				<programmerole guid="script-roles-ger-021" first_name="Klaus" last_name="Rudzinski" gender="1" country="D" />
			</programmeroles>
		</tvtdb>
		'''.noErrors
	}

	@Test
	def void singleDoubleQuoteOverride() {
		'''
		<?xml version="1.0" encoding="utf-8"?>
		<tvtdb>
			<version value="3" />
			<allprogrammes>
				<programme id="id" product="2" >
					<title>
						<de>Titel mit 5.25"-Diskette</de>
					</title>
				</programme>
			</allprogrammes>
		</tvtdb>
		'''.noErrors
	}

	def void noErrors(CharSequence content){
		val result = parseHelper.parse(content)
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
