/*
 * generated by Xtext 2.23.0
 */
package org.tvtower.db;

import org.eclipse.xtext.parser.antlr.Lexer;
import org.eclipse.xtext.parser.antlr.LexerBindings;
import org.eclipse.xtext.parser.antlr.LexerProvider;
import org.eclipse.xtext.resource.IResourceServiceProvider;
import org.tvtower.db.parser.antlr.internal.InternalDatabaseLexer;
import org.tvtower.db.resource.DatabaseResourceServiceProvider;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DatabaseRuntimeModule extends AbstractDatabaseRuntimeModule {

	public Class<? extends IResourceServiceProvider> bindDatabaseResourceServiceProvider() {
		return DatabaseResourceServiceProvider.class;
	}

	@Override
	public Class<? extends Lexer> bindLexer() {
		return CustomDatabaseLexer.class;
	}

	@Override
	public Provider<? extends InternalDatabaseLexer> provideInternalDatabaseLexer() {
		return LexerProvider.create(CustomDatabaseLexer.class);
	}
	
	@Override
	public void configureRuntimeLexer(Binder binder) {
		binder.bind(Lexer.class)
			.annotatedWith(Names.named(LexerBindings.RUNTIME))
			.to(CustomDatabaseLexer.class);
	}
}
