/*
 * generated by Xtext 2.23.0
 */
package org.tvtower.db.ui.labeling;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.tvtower.db.constants.Constants;
import org.tvtower.db.constants.NewsType;
import org.tvtower.db.database.Achievement;
import org.tvtower.db.database.Achievements;
import org.tvtower.db.database.Advertisement;
import org.tvtower.db.database.Advertisements;
import org.tvtower.db.database.CelebrityPeople;
import org.tvtower.db.database.InsignificantPeople;
import org.tvtower.db.database.LanguageString;
import org.tvtower.db.database.News;
import org.tvtower.db.database.NewsItem;
import org.tvtower.db.database.Person;
import org.tvtower.db.database.Programme;
import org.tvtower.db.database.ProgrammeRole;
import org.tvtower.db.database.ProgrammeRoles;
import org.tvtower.db.database.Programmes;
import org.tvtower.db.database.ScriptTemplate;
import org.tvtower.db.database.ScriptTemplates;
import org.tvtower.db.database.Title;
import org.tvtower.db.resource.PersonUtil;

import com.google.inject.Inject;

/**
 * Provides labels for EObjects.
 * 
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class DatabaseLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public DatabaseLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(Achievements achievements) {
		return "Achievements";
	}

	String text(Achievement a) {
		String title = fromTitle(a.getTitle());
		if (title != null) {
			return title;
		}
		return a.getName();
	}

	String text(Advertisements achievements) {
		return "Advertisements";
	}

	String text(Advertisement a) {
		String title = fromTitle(a.getTitle());
		if (title != null) {
			return title;
		}
		return a.getName();
	}

	String text(News news) {
		return "News";
	}

	String text(NewsItem i) {
		String prefix = "";
		if (NewsType.INITIAL_NEWS.equals(i.getType())) {
			if("0".equals(i.getData().getAvailable())) {
				prefix = "(--) ";
			}else if (Constants.newsFlag.hasFlag(i.getData().getFlags(), 2)) {
				prefix = "(1x) ";
			} else {
				prefix = "(\u221E) ";
			}
		}
		String title = fromTitle(i.getTitle());
		if (title != null) {
			return prefix + title;
		}
		return prefix + i.getName();
	}

	String image(NewsItem ele) {
		if (ele.getData() != null && ele.getData().getGenre() != null) {
			return "news/genre" + ele.getData().getGenre() + ".png";
		}
		return null;
	}

	String text(Programmes programmes) {
		return "Programmes";
	}

	String text(Programme p) {
		String title = fromTitle(p.getTitle());
		if (title != null) {
			return title;
		}
		return p.getName();
	}

	String text(ScriptTemplates programmes) {
		return "ScriptTemplates";
	}

	String text(ScriptTemplate t) {
		String title = fromTitle(t.getTitle());
		if (title != null) {
			return title;
		}
		return t.getName();
	}

	String text(CelebrityPeople celebrities) {
		return "Celebrities";
	}

	String text(InsignificantPeople otherPeople) {
		return "other People";
	}

	String text(ProgrammeRoles roles) {
		return "Roles";
	}

	String text(ProgrammeRole role) {
		String result = PersonUtil.fromNames(role.getLastName(), role.getFirstName());
		if (result != null) {
			return result;
		}
		return role.getName();
	}

	String text(Person p) {
		String result = PersonUtil.displayName(p);
		if (result != null) {
			return withFictional(p, result);
		}
		return withFictional(p, p.getName());
	}

	String image(Person p) {
		return (PersonUtil.isFictional(p) ? "fictional" : "real") + ".png";
	}

	private String withFictional(Person p, String name) {
		return name + (PersonUtil.isFictional(p) ? " (fictional)" : " (real)");
	}

	private String fromTitle(Title t) {
		if (t != null) {
			if(t.getGlobal()!=null) {
				return t.getGlobal();
			}
			EList<LanguageString> lStrings = t.getLstrings();
			if (!lStrings.isEmpty()) {
				return lStrings.get(0).getText();
			}
		}
		return null;
	}

	// Labels and icons can be computed like this:

//	String text(Greeting ele) {
//		return "A greeting to " + ele.getName();
//	}
//
//	String image(Greeting ele) {
//		return "Greeting.gif";
//	}
}
